SELECT
    B.TITLE,
    B.BOARD_ID,
    A.REPLY_ID,
    A.WRITER_ID,
    A.CONTENTS,
    TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM
    USED_GOODS_REPLY A
JOIN
    USED_GOODS_BOARD B ON A.BOARD_ID = B.BOARD_ID
WHERE
    B.CREATED_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
ORDER BY
    A.CREATED_DATE ASC,
    B.TITLE ASC;